# Generated by Django 3.1.5 on 2021-02-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='question',
            new_name='guild',
        ),
    ]
